<a href="https://colab.research.google.com/github/uuuno/pytorch_tutorial/blob/master/1_1_WhatIsPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

## Tensors

In [6]:
# 5*3のマトリックス（Uninitialized）
x = torch.empty(5,3)
print(x.shape, "\n", x)

torch.Size([5, 3]) 
 tensor([[3.8170e-36, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.8888e+31],
        [1.4153e-43, 0.0000e+00, 0.0000e+00]])


In [7]:
# 5*3のマトリックス（Initialized）
x = torch.rand(5,3)
print(x.shape, "\n", x)

torch.Size([5, 3]) 
 tensor([[0.1721, 0.3646, 0.6238],
        [0.3570, 0.6998, 0.9890],
        [0.7933, 0.5434, 0.9175],
        [0.0074, 0.5184, 0.6918],
        [0.6375, 0.4152, 0.0831]])


In [16]:
# Arrayを直接テンソルに変換
arr = np.random.rand(5,3)
x = torch.tensor(arr)
print(x)

tensor([[0.2945, 0.4978, 0.4205],
        [0.6320, 0.4850, 0.4197],
        [0.3541, 0.4116, 0.0038],
        [0.3376, 0.9482, 0.0673],
        [0.0734, 0.8413, 0.6474]], dtype=torch.float64)


In [39]:
# 既存のテンソルの形を利用する
print(x.shape)

x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x)
print(x)

torch.Size([5, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1496,  0.1295, -1.6348],
        [ 0.5451, -0.5521,  2.6679],
        [ 0.5834,  0.0338,  0.3902],
        [-1.3855, -0.0426,  0.1882],
        [ 0.3443, -0.2823,  0.1016]], dtype=torch.float64)


In [43]:
# size確認
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


##Operations

In [0]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [50]:
# 足し算(4つの方法)
print(x + y)  # １

print(torch.add(x, y))  # 2

result = torch.empty(2, 2)  # 3
torch.add(x, y, out=result)
print(result)

y.add_(x)  # 4
print(y)

tensor([[0.5293, 0.3494],
        [1.3372, 0.9727]])
tensor([[0.5293, 0.3494],
        [1.3372, 0.9727]])
tensor([[0.5293, 0.3494],
        [1.3372, 0.9727]])
tensor([[0.5293, 0.3494],
        [1.3372, 0.9727]])


In [59]:
# Indexing (numpyと同じ)
print(x)
print(x[:, 1])

tensor([[0.3183, 0.2887],
        [0.8186, 0.1502]])
tensor([0.2887, 0.1502])


In [63]:
# Resizing
x = torch.rand(4, 4)
y = x.view(1, 16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([1, 16]) torch.Size([2, 8])


In [68]:
# One-Element tensorの取り出し
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.5182])
-1.5182119607925415


## Numpy Bridge

In [89]:
# torch tensor --> Numpy array
a = torch.ones(5)
print(a)

b = a.numpy() # .numpyにすると値が共有される（どちらも更新される）
print(b)

c = np.array(a) # 普通のパースではただのcopy
print(c)


a.add_(1)
print(a)
print(b)
print(c)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]


In [98]:
# numpy array --> torch tensor
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [100]:
torch.cuda.is_available()

False